# Generated by Django 6.0.2 on 2026-02-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundoImobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('preco_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preco_teto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ultimo_dividendo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_patrimonial', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('variacao', models.FloatField(default=0.0)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
