# Generated by Django 6.0.2 on 2026-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoimobiliario',
            name='tipo',
            field=models.CharField(default='Não Definido', max_length=30),
        ),
    ]
